// Player configuration
// Re-exports from shared constants for module-local access

export {
  PLAYER_SPEED,
  PLAYER_RADIUS,
  PLAYER_MAX_HEALTH,
  PLAYER_HEALTH_REGEN_RATE,
  PLAYER_ROTATION_SPEED,
  PLAYER_ATTACK_SPEED_MULTIPLIER,
  SWORD_DAMAGE,
  SWORD_REACH,
  SLASH_DURATION,
  SLASH_SWEEP_ANGLE,
  ATTACK_COOLDOWN,
  SLASH_HOLD_DURATION,
  COMBO_RESET_TIME,
  IFRAME_DURATION,
  DASH_SPEED,
  DASH_DURATION,
  DASH_COOLDOWN,
  DAMAGE_VARIANCE,
} from '@curious/shared';
