// Enemy configuration
// Re-exports from shared constants for module-local access

export {
  ENEMY_SPEED,
  ENEMY_RADIUS,
  ENEMY_MAX_HEALTH,
  ENEMY_AGGRO_RANGE,
  ENEMY_LEASH_RANGE,
  ENEMY_ATTACK_RANGE,
  ENEMY_ATTACK_COOLDOWN,
  ENEMY_PUNCH_DAMAGE,
  ENEMY_PUNCH_DURATION,
  ENEMY_RESPAWN_DELAY,
  ENEMY_ACTIVE_COUNT,
  ENEMY_DESIRED_DISTANCE,
  ENEMY_SEPARATION_RADIUS,
  ENEMY_SEPARATION_FORCE,
} from '@curious/shared';
